name: mps
description: A new Flutter project.



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  firebase_auth:
  firebase_core: ^1.0.3
  firebase_storage: ^8.1.0
  google_sign_in:
  shared_preferences:
  random_string:
  cloud_firestore:
  geocoding:
  geolocator: ^7.0.3
  google_maps_webservice:
  http:
  google_maps_controller: ^1.2.0
  provider:
  carousel_slider: ^3.0.0
  mockito: ^5.0.9
  firebase_auth_mocks: ^0.6.0


  flutter_polyline_points:
  google_maps_flutter:
  rxdart: any
  geoflutterfire:
  location:
  uuid: 3.0.4

  cupertino_icons: ^1.0.2

  file_picker: ^3.0.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true

  assets: 
  - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
